# Generated by Django 3.1.7 on 2021-08-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20210810_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='author',
            name='author_bio',
            field=models.CharField(default='n/a', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=50),
        ),
    ]
