# Generated by Django 3.1.7 on 2021-08-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_quote_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='quotes.author'),
        ),
    ]
