# Generated by Django 3.1.7 on 2021-08-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quote_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotes.author'),
        ),
    ]
