# Generated by Django 3.1.7 on 2021-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20210813_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_bio',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
