CREATE OR ALTER VIEW [dbo].[V_PLAYERS_TEAM2]
AS
SELECT
	[SPELERSNR]
FROM
	[dbo].[WEDSTRIJDEN]
WHERE
	[TEAMNR] = 2
;
GO

CREATE OR ALTER VIEW [dbo].[V_AVERAGE_FINE_AMOUNT]
AS
SELECT
	AVG([BEDRAG]) AS AVERAGEAMOUNT
FROM
	[dbo].[BOETES]
WHERE
	[SPELERSNR] IN 
	(
		SELECT * FROM [dbo].[V_PLAYERS_TEAM2]
	)
;
GO

SELECT DISTINCT 
	[SPELERSNR]
FROM
	[dbo].[BOETES]
WHERE
	[BEDRAG] > (SELECT [AVERAGEAMOUNT] FROM [dbo].[V_AVERAGE_FINE_AMOUNT]);