CREATE OR ALTER PROCEDURE [dbo].[SP_GET_PLAYER_FINESCOUNT]
	@prm_spelersnr INT
AS
BEGIN
	SELECT
		COUNT(*)
	FROM
		[dbo].[BOETES]
	WHERE
		[SPELERSNR] = @prm_spelersnr
END;
GO

EXEC [dbo].[SP_GET_PLAYER_FINESCOUNT] 44;
GO