# Generated by Django 3.1.7 on 2021-08-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20210813_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_author',
            field=models.ForeignKey(default='n/a', on_delete=django.db.models.deletion.CASCADE, to='quotes.author'),
            preserve_default=False,
        ),
    ]
