# Generated by Django 3.1.7 on 2021-08-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20210813_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_author',
        ),
    ]
