CREATE INDEX [IX_BESTUURSLEDEN_FUNCTIE] ON [dbo].[BESTUURSLEDEN]
(
	[FUNCTIE]
)

CREATE INDEX [IX_TEAMS_SPELERSNR] ON [dbo].[TEAMS]
(
	[SPELERSNR]
)

CREATE INDEX [UIX_BESTUURSLEDEN_1] ON [dbo].[BESTUURSLEDEN]
(
	[BEGIN_DATUM],
	[FUNCTIE]
)

DROP INDEX [UIX_BESTUURSLEDEN_1] ON [dbo].[BESTUURSLEDEN]

DROP INDEX [IX_BESTUURSLEDEN_FUNCTIE] ON [dbo].[BESTUURSLEDEN]