# Generated by Django 3.1.6 on 2021-03-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_paswoord',
            new_name='user_password',
        ),
    ]
