CREATE OR ALTER VIEW [dbo].[V_PLAYERS_PERTEAM]
AS
SELECT 
	[t].[TEAMNR],
	(
		SELECT
			COUNT(DISTINCT [SPELERSNR])
		FROM
			[dbo].[WEDSTRIJDEN] [w]
		WHERE
			[w].[TEAMNR] = [t].[TEAMNR]
	) AS [GAMESPLAYED]
FROM
	[dbo].[TEAMS] [t]
;
GO

SELECT * FROM [dbo].[V_PLAYERS_PERTEAM];
GO
