CREATE OR ALTER VIEW [dbo].[V_PLAYERS_RETIRED]
AS
SELECT 
	*
FROM
	[dbo].[SPELERS] [s]
WHERE
	(
		DATEDIFF(yy, [s].[GEB_DATUM], GETDATE()) = 65 AND
		DATEPART(dayofyear, GETDATE()) >= DATEPART(dayofyear, [s].[GEB_DATUM])
	)
	OR
	(
		DATEDIFF(yy, [s].[GEB_DATUM], GETDATE()) > 65
	)
;
GO

SELECT * FROM [dbo].[V_PLAYERS_RETIRED];
GO
