# Generated by Django 3.1.6 on 2021-03-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=40)),
                ('user_paswoord', models.CharField(max_length=15)),
            ],
        ),
    ]
